name: kisangro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

# -------------------- DEPENDENCIES --------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  video_player: 2.8.6
  uuid: ^4.5.1
  http: ^1.4.0
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.13.0
  geolocator: ^12.0.0
  device_info_plus: ^12.3.0
  google_fonts: ^7.0.0
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.3.3
  json_annotation: ^4.9.0
  connectivity_plus: ^7.0.0
  record: ^6.1.0
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.1
  shimmer: ^3.0.0
  collection: ^1.19.1
  dotted_border: ^2.1.0
  cached_network_image: ^3.4.1
  razorpay_flutter: ^1.4.0
  audioplayers: ^6.1.0
  flutter_sound: ^9.28.0
  confetti: ^0.8.0
  http_parser: ^4.1.2

  # PDF & File
  pdf: ^3.11.0
  syncfusion_flutter_core: ^32.1.22
  syncfusion_flutter_pdf: ^32.1.22
  syncfusion_flutter_pdfviewer: ^32.1.22
  syncfusion_flutter_signaturepad: ^32.1.22
  file_picker: ^8.0.6
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1





  # UI & UX
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.0
  intl_phone_field: ^3.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  create_date_picker: ^1.0.2
  smooth_page_indicator: ^1.1.0
  geocoding: ^3.0.0
  flutter_rating_bar: ^4.0.0
  youtube_player_flutter: ^9.1.3
  flutter_local_notifications: ^20.1.0

# -------------------- DEV DEPENDENCIES --------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

# -------------------- APP ICON --------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# -------------------- FLUTTER CONFIG --------------------
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cart.gif
    - assets/kyc1.gif
    - assets/process.gif
    - assets/wings.gif
    - assets/verified.gif
    - assets/delivery.gif
    - assets/coin.gif
    - assets/wish.gif
    - assets/logout.gif
    - assets/complaint.gif
    - assets/delete.gif
    - assets/logo3.svg
    - assets/Welcome1.svg
    - assets/welcome2.svg
    - assets/welcome3.svg
    - assets/welcome4.svg
    - assets/skip.svg
    - assets/audio/notification.mp3
